name: Bug Report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - name: Firefox
          labels: ['Firefox']
        - name: Chrome
          labels: ['Chrome']
        - name: Safari
          labels: ['Safari']
        - name: Microsoft Edge
          labels: ['Microsoft Edge']



