version: '3.4'

services:
  web:
    restart: always
    container_name: tickets_web
    image: tickets_web:latest
    build: .
    command: ash -c "python manage.py migrate && gunicorn -w 5 tickets_project.wsgi --timeout=500 -b 0.0.0.0:5000"
    expose:
      - "5000"
    volumes:
      - static:/app/static
    networks:
      - tickets
  nginx:
    restart: always
    container_name: tickets_nginx
    image: tickets_nginx:latest
    build:
        context: .
        dockerfile: Dockerfile-nginx
    volumes:
      - static:/app/static
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - tickets

volumes:
  static:
    name: tickets_static

networks:
  tickets:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16