# Generated by Django 4.2.5 on 2023-10-31 20:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ticket_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Not Used', max_length=50)),
                ('finish_date', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField()),
                ('type_ticket', models.CharField(default='Day', max_length=50)),
            ],
            options={
                'ordering': ['-ticket_date'],
            },
        ),
    ]
